name: Trigger auto deployment for code-detect

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [epic-1]
    paths:
      - "**"
      - ".github/workflows/code-detect-AutoDeployTrigger-5b287358-2951-46c6-bf01-d453bba55f4b.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CODEDETECT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CODEDETECT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CODEDETECT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.workspace }}
          file: codeDetect/Dockerfile
          push: true
          tags: docpulseresgistry.azurecr.io/code-detect:latest
          registry: docpulseresgistry.azurecr.io
          username: ${{ secrets.CODEDETECT_REGISTRY_USERNAME }}
          password: ${{ secrets.CODEDETECT_REGISTRY_PASSWORD }}

      - name: Deploy to Azure Container Apps
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az containerapp update \
              --name code-detect \
              --resource-group DocPulse \
              --image docpulseresgistry.azurecr.io/code-detect:latest \
              --registry-server docpulseresgistry.azurecr.io \
              --registry-username ${{ secrets.CODEDETECT_REGISTRY_USERNAME }} \
              --registry-password ${{ secrets.CODEDETECT_REGISTRY_PASSWORD }}
